# Generated by Django 3.1.4 on 2021-01-12 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0, verbose_name='Год')),
                ('profit', models.IntegerField(default=0, verbose_name='Чистая Прибыль (млн.$)')),
                ('expense', models.IntegerField(default=0, verbose_name='Расходы (млн.$)')),
            ],
            options={
                'verbose_name': 'Отчет',
                'verbose_name_plural': 'Отчеты',
            },
        ),
        migrations.AlterModelOptions(
            name='processor',
            options={'verbose_name': 'Процессор', 'verbose_name_plural': 'Процессоры'},
        ),
        migrations.AlterField(
            model_name='processor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='report',
            name='processor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.processor', verbose_name='ID Процессора'),
        ),
    ]
